// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(QuanLyPhongMach))]
    partial class QuanLyPhongMachModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("ApplicationCore.Entities.Benh", b =>
                {
                    b.Property<int>("MaBenh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenBenh")
                        .HasColumnType("TEXT");

                    b.HasKey("MaBenh");

                    b.ToTable("Benh");
                });

            modelBuilder.Entity("ApplicationCore.Entities.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.HasKey("MaBenhNhan");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("SoThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DonThuocMaDonThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaDonThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("REAL");

                    b.Property<int?>("ThuocMaThuoc")
                        .HasColumnType("INTEGER");

                    b.HasKey("SoThuTu");

                    b.HasIndex("DonThuocMaDonThuoc");

                    b.HasIndex("ThuocMaThuoc");

                    b.ToTable("ChiTietDonThuoc");
                });

            modelBuilder.Entity("ApplicationCore.Entities.DonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaPhieuKham")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhieuKhamMaPhieuKham")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TongTien")
                        .HasColumnType("REAL");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex("PhieuKhamMaPhieuKham");

                    b.ToTable("DonThuoc");
                });

            modelBuilder.Entity("ApplicationCore.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatKhau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VaiTroMaVaiTro")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("VaiTroMaVaiTro");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PhieuKham", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BenhNhanMaBenhNhan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayKham")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NhanVienMaNhanVien")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrieuChung")
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhieuKham");

                    b.HasIndex("BenhNhanMaBenhNhan");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("PhieuKham");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThuoc")
                        .HasColumnType("TEXT");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuoc");
                });

            modelBuilder.Entity("ApplicationCore.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenVaiTro")
                        .HasColumnType("TEXT");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ChiTietDonThuoc", b =>
                {
                    b.HasOne("ApplicationCore.Entities.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("DonThuocMaDonThuoc");

                    b.HasOne("ApplicationCore.Entities.Thuoc", "Thuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("ThuocMaThuoc");
                });

            modelBuilder.Entity("ApplicationCore.Entities.DonThuoc", b =>
                {
                    b.HasOne("ApplicationCore.Entities.PhieuKham", "PhieuKham")
                        .WithMany("DonThuocs")
                        .HasForeignKey("PhieuKhamMaPhieuKham");
                });

            modelBuilder.Entity("ApplicationCore.Entities.NhanVien", b =>
                {
                    b.HasOne("ApplicationCore.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("VaiTroMaVaiTro");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PhieuKham", b =>
                {
                    b.HasOne("ApplicationCore.Entities.BenhNhan", "BenhNhan")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("BenhNhanMaBenhNhan");

                    b.HasOne("ApplicationCore.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("NhanVienMaNhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
